djangoSchool/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.contrib.auth.views import login, logout
from rest_framework import routers


urlpatterns = [
	url(r'^$','djangoSchool.views.home',name="home"),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^attendance/',include('attendance.urls', namespace="attendance")),
	url(r'^notice/',include('notice.urls', namespace="notice")),
	url(r'^marks/',include('marks.urls', namespace="marks")),
	url(r'^accounts/', include('accounts.urls',namespace="accounts")),
	url(r'^records/', include('records.urls',namespace="records")),
	url(r'^myapi/', include('mywrapper.urls',namespace="mywrapper")),
	url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
	url(r'^attendance2/',include('attendance2.urls', namespace="attendance2")),
]

marks/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$',views.index,name='index'),
	url(r'^viewMarks/(?P<classSection>c[0-9]+[A-Z])/$', views.viewMarks, name='viewMarks'),
	url(r'^viewMarks/(?P<classSection>cNursery[A-Z])/$', views.viewMarks, name='viewMarks'),
	url(r'^enterMarks/(?P<classSection>c[0-9]+[A-Z])/$', views.enterMarks, name='enterMarks'),
	url(r'^enterMarks/(?P<classSection>cNursery[A-Z])/$', views.enterMarks, name='enterMarks'),
]

records/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$',views.index,name='index'),
	url(r'^enterStudents/(?P<classSection>c[0-9]+[A-Z])/$', views.enterStudents, name='enterStudents'),
	url(r'^enterStudents/(?P<classSection>cNursery[A-Z])/$', views.enterStudents, name='enterStudents'),
]

records/models.py
from django.db import models

# Create your models here.

records/views.py
from django.shortcuts import render
# Create your views here.
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import render_to_response
from django.http import HttpResponse
import json,httplib,urllib
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.mail import EmailMessage
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseBadRequest, JsonResponse
from django import forms
from django.template import RequestContext
import django_excel as excel
import pyexcel.ext.xls
import pyexcel.ext.xlsx
import pyexcel
import urllib
from attendance.models import ListOfClasses
from datetime import datetime
from django.contrib.auth.models import User
from attendance.models import ListOfClasses


def getStudentList(classSection,restKey,appKey):
	connection = httplib.HTTPSConnection('api.parse.com', 443)
	params = urllib.urlencode({"where":json.dumps({
		   "Class_Name": '%s' % classSection
		 })})
	connection.connect()
	connection.request('GET', '/1/classes/Class?%s' % params, '', {
		   # "X-Parse-Application-Id": "Sqj2XR5GDdMcXuMsffDQ9yEdzhYJqBZYvDSMLqFC",
		   # "X-Parse-REST-API-Key": "Ox5FKRyiEM33GzS7Ka6oTJCXRIjiPghotbD9dWPx",
		   "X-Parse-Application-Id": appKey,
		   "X-Parse-REST-API-Key": restKey
		 })
	result = json.loads(connection.getresponse().read())
	# print result
	return result['results'][0]['Student_Name']


def postClassTable(json_data,theclass,theuser,restKey,appKey,javaKey,masterKey):
	connection = httplib.HTTPSConnection('api.parse.com', 443)
	connection.connect()
	connection.request('POST', '/1/classes/Class', json_data, {
		   "X-Parse-Application-Id": appKey,
		   "X-Parse-REST-API-Key": restKey,
		   "Content-Type": "application/json"
		 })
	results = json.loads(connection.getresponse().read())
	q=ListOfClasses(schoolUser=theuser,someClass=theclass,appKey=appKey,restKey=restKey, javaKey=javaKey, masterKey=masterKey)
	q.save()

	#print results

def postListClassTable(classNumber,classSection,restKey,appKey,masterKey):
	# Change Schema
	print masterKey
	fullname = 'c' + classNumber + classSection
	partname = classNumber + classSection 
	data = {}
	data['className'] = "List_Class"
	data['fields'] = {}
	data['fields'][fullname] = {}
	data['fields'][fullname]['type'] = "Array"
	json_data = json.dumps(data)
	print json_data 
	connection = httplib.HTTPSConnection('api.parse.com', 443)
	connection.connect()
	connection.request('PUT', '/1/schemas/List_Class', json_data, {
	       "X-Parse-Application-Id": appKey,
	       "X-Parse-Master-Key": masterKey,
	       "Content-Type": "application/json"
	     })
	print "Changing the schema"
	result = json.loads(connection.getresponse().read())
	print result

	# Update
	data = {}
	data["Class_List"] = {}
	data["Class_List"]["__op"] = "AddUnique"
	data["Class_List"]["objects"] = [partname]
	data[fullname] = {}
	data[fullname]["__op"] = "AddUnique"
	data[fullname]["objects"] = ["English", "Hindi"]
	json_data = json.dumps(data)
	connection = httplib.HTTPSConnection('api.parse.com', 443)
	connection.connect() 
	connection.request('PUT', '/1/classes/List_Class/1hKtVUxgOI', json_data, {
	   "X-Parse-Application-Id": appKey,
	   "X-Parse-REST-API-Key": restKey,
	   "Content-Type": "application/json"
	 })
	result = json.loads(connection.getresponse().read())
	print result

	
@login_required
def index(request):
	latest_class_list = ListOfClasses.objects.filter(schoolUser=request.user)	
	classLinks = [p.someClass for p in latest_class_list]
	classNames = [p[1:-1] + " " + p[-1] for p in classLinks]
	zipped_data = zip(classLinks, classNames)
	firstInstance = ListOfClasses.objects.filter(schoolUser=request.user).first()
	restKey = firstInstance.restKey
	javaKey = firstInstance.javaKey
	appKey 	= firstInstance.appKey
	masterKey = firstInstance.masterKey
	context = {'item1':"My first string",'classLinks':classLinks,'classNames':classNames,'zipped_data':zipped_data}
	if request.method == 'POST':
		classNumber = request.POST['classNumber']
		classSection = request.POST['classSection']
		data = {}
		data['Class_Name'] = 'c' + request.POST['classNumber'] + request.POST['classSection']
		data['Student_Name'] = []
		json_data = json.dumps(data)
		postClassTable(json_data,data['Class_Name'],request.user,restKey,appKey,javaKey,masterKey)		
		postListClassTable(classNumber,classSection,restKey,appKey,masterKey)
		context['alert'] = 'alert'
		return render(request,'records/list.html',context)
	else:
		return render(request,'records/list.html',context)	

@login_required
def enterStudents(request,classSection):
	latest_class_list = ListOfClasses.objects.filter(schoolUser=request.user)	
	classLinks = [p.someClass for p in latest_class_list]
	classNames = [p[1:-1] + " " + p[-1] for p in classLinks]
	zipped_data = zip(classLinks, classNames)
	firstInstance = ListOfClasses.objects.filter(schoolUser=request.user).first()
	restKey = firstInstance.restKey
	javaKey = firstInstance.javaKey
	appKey 	= firstInstance.appKey
	studentList = getStudentList(classSection,restKey,appKey)
	studentRoll = list(p.split()[0] for p in studentList)
	counterOfPreviousStudents = len(studentRoll) + 1
	studentFirstName = list(p.split()[1] for p in studentList)
	studentLastName = []
	for p in studentList:
		try:
			x = p.split()[2:]
			x = ' '.join(x)
			studentLastName.append(x)
		except:
			studentLastName.append('')
	zipped_student = zip(studentRoll,studentFirstName,studentLastName)
	# print studentRoll
	# print studentFirstName
	# print studentLastName
	# return HttpResponse("return this string")

	if request.method == 'POST':
		userNames = getUsernames(classSection,restKey,appKey)
		absentStudents = request.POST
		data = {}
		data['cDate'] = request.POST['date']
		dateOfAttendance = data['cDate']
		myDateObject = datetime.strptime(dateOfAttendance,'%d/%m/%Y')
		myDateObject = myDateObject.strftime("%d %B %Y")
		# For loop to iterate over list of students and assign 'A' or 'P'.
		# Also sends emails to absent students' parents
		for student in studentList:
			studentMod = student.replace (" ", "_")
			studentMod = "R" + studentMod
			if(student in absentStudents):
				data[studentMod] = "A"
				userdata = (user for user in userNames if user["username"] == classSection+student).next()
				# if 'email' in userdata:
				# 	print 'email the person!'
				# 	email = EmailMessage('Hello there', 'well well, your son was absent today', to=[userdata['email']])
				# 	print userdata['email']
				# 	email.send()
				# else:
				# 	print 'ask them to enter their e-mail!'
				if 'phoneNumber' in userdata:
					# print 'Starting now'
					try:
						childName = userdata["username"].split()
						childName = childName[1] +  " " + childName[2]
					except:
						childName = "Your child"
					myMessage =  childName + ' was absent on ' + myDateObject
					myNumber = userdata['phoneNumber']
					# print 'Is this where I go wrong?'
					params = urllib.urlencode({'user': 'Saurabh', 'password': '123@123', 'mobiles': myNumber, 'sms':myMessage,'senderid':'PTMNOW','version':3})
					# print 'Or here?'
					f = urllib.urlopen("http://trans.profuseservices.com/sendsms.jsp?%s" % params)
					print f.read()
			else:
				data[studentMod] = "P"
		start = dateOfAttendance.find('/')
		end = dateOfAttendance.rfind('/')
		data['mdate'] = int(dateOfAttendance[start+1:end])
		json_data = json.dumps(data)
		postAttendanceData(classSection,json_data,restKey,appKey)					
		# return HttpResponseRedirect(reverse('attendance:index'))
		#return redirect(reverse('attendance:index'), {'alert':'alert'})
		return render(request,'attendance/list.html',{'alert':'alert',"classSection":classSection,'classLinks':classLinks,'classNames':classNames,'zipped_data':zipped_data})
	else:	
		neatSection = classSection[1:-1] + " " + classSection[-1]
		strippedSection = classSection[1:]
		# print zipped_student
		context = {'classSection':classSection,'neatSection':neatSection,'strippedSection':strippedSection,'studentList':studentList,'appKey':appKey,'javaKey':javaKey,'zipped_student':zipped_student,'my_range': range(counterOfPreviousStudents,80)}
		return render(request,'records/enterStudents.html',context)








######## Misc Commented Code ################

	# connection.connect()
	# connection.request('GET', '/1/classes/List_Class', '', {
	# 	   "X-Parse-Application-Id": appKey,
	# 	   "X-Parse-REST-API-Key": restKey,
	# 	   "Content-Type": "application/json"
	# 	 })
	# results = json.loads(connection.getresponse().read())
	# results = results['results'][0]
	# results['c' + classNumber + classSection] = ['Hindi','English']
	# results['Class_List'].append(classNumber+classSection)
	# del results['createdAt']
	# del results['updatedAt']
	# objectID = results["objectId"]
	# del results['objectId']
	# json_data = json.dumps(results)
	# # Delete old record
	# connection = httplib.HTTPSConnection('api.parse.com', 443)
	# connection.connect()
	# connection.request('DELETE', '/1/classes/List_Class/'+objectID, json_data, {
	# 	   "X-Parse-Application-Id": appKey,
	# 	   "X-Parse-REST-API-Key": restKey,
	# 	   "Content-Type": "application/json"
	# 	 })
	# results = json.loads(connection.getresponse().read())
	# print "Delete:"
	# print results


	# # Add new data
	# connection = httplib.HTTPSConnection('api.parse.com', 443)
	# connection.connect()
	# connection.request('POST', '/1/classes/List_Class', json_data, {
	# 	   "X-Parse-Application-Id": appKey,
	# 	   "X-Parse-REST-API-Key": restKey,
	# 	   "Content-Type": "application/json"
	# 	 })
	# results = json.loads(connection.getresponse().read())
	# print "Insert:"
	# print results

records/templates/records/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="/static/ico/favicon.png">
  <title>{% block title %}{% endblock %}</title>
  <style type="text/css">
    body {
      min-height: 2000px;
      padding-top: 70px;
    }
    .tableFloatingHeaderOriginal th {
      background-color: #fff;
      border-bottom: 1px solid #DDD;
    }
  </style>
  <!-- Bootstrap core CSS -->
  <link href="/static/css/bootstrap.min.css" rel="stylesheet">
  <!-- Custom styles for this template -->
  <link href="/static/css/dashboard.css" rel="stylesheet">
  <link href="/static/css/jquery-ui.min.css" rel="stylesheet">
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
      <script src="/static/js/date.js"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
      <script src="/static/js/jquery-ui.min.js"></script>

      <script type="text/javascript" src="http://www.parsecdn.com/js/parse-latest.js"></script>
      <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.0/css/bootstrap-toggle.min.css" rel="stylesheet">
      <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.0/js/bootstrap-toggle.min.js"></script>
      <script src="/static/js/jquery.stickytableheaders.min.js"></script>
      <script src="/static/js/bootstrap.min.js"></script>
      <script src="/static/js/sweetalert.min.js"></script> 
      <link rel="stylesheet" type="text/css" href="/static/css/sweetalert.css">

    </head>

    <body>
      <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid" style="border-bottom: 1px solid darkblue">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="#">School Home</a></li>
              <li><a href="/accounts/logout">Log out</a></li>
            </ul>
            <div class="logoWrapper" style="padding: 25px ">
              <img src="/static/images/sftwaredev_thumb.gif" alt="BITS Pilani logo">
            </div>
          </div>
        </div>
      </nav>

      <div class="container-fluid"  >
        <div class="row">
          <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
              <li><a href="{% url 'attendance:index' %}">Class Attendance</a></li>
              <li><a href="{% url 'notice:index' %}">Notice Board</a></li>
              <li><a href="{% url 'marks:index' %}">Academic Performance</a></li>
            </ul>

            {% block highlighted_block %}{% endblock %}
        
            
          </div>

          <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            {% block content %} {% endblock %}
          </div>
        </div>
      </div>

      {% block script %}
      {% endblock %}

  </body>
  </html>

records/templates/records/enterStudents.html
{% extends 'attendance/base.html' %}
{% block title %}Enter Attendance for {{neatSection}} {% endblock %}

{% block content %}
<h1 class="page-header">{{neatSection}}</h1>
<hr>
<form action="{% url 'records:enterStudents' classSection %}" method="post">
<table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>Roll number</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Mobile number</th>
      </tr>
    </thead>
    <tbody>
{% for roll,first,last in zipped_student %}
<tr>
        <td><div class="form-group">
  			<input type="text" name="{{roll}}Roll" value="{{roll}}">
		</div></td>

        <td><div class="form-group">
  			<input type="text" name="{{roll}}First" value="{{first}}">
		</div></td>

		<td><div class="form-group">
  			<input type="text" name="{{roll}}Last" value="{{last}}">
		</div></td>

<!-- 		<td><div class="form-group">
  			<input type="text" name="{{roll}}Third" value="{{first}}">
		</div></td> -->

    </tr>
{% endfor %}

{% for i in my_range %}
<tr>
        <td><div class="form-group">
  			<input type="text" name="{{i}}BlankRoll" value="{{i}}">
		</div></td>

        <td><div class="form-group">
  			<input type="text" name="{{i}}BlankFirst" value="">
		</div></td>

		<td><div class="form-group">
  			<input type="text" name="{{i}}BlankLast" value="">
		</div></td>

<!-- 		<td><div class="form-group">
  			<input type="text" name="{{roll}}Third" value="{{first}}">
		</div></td> -->

    </tr>
{% endfor %}



</tbody>
  </table>

<input type="submit" value="Submit Attendance" class="btn btn-primary btn-block" role="button">

</form>
{% endblock %}

records/templates/records/list.html
{% extends 'records/base.html' %}
{% block title %}Select class of which to edit student information {% endblock %}
{% block highlighted_block %}
            <ul class="nav nav-sidebar">
              <li class="active"><a href="">Add/Edit Student Information<span class="sr-only">(current)</span></a></li>
              <li><a href="">Change password</a></li>
              <li><a href="">Help</a></li>
            </ul>  
{% endblock %}
{% block content %}
<h1 class="page-header">Please pick a class from the list</h1>
<div class="list-group" id="myList">
{% for classLink,className in zipped_data %}
  <a href="{% url 'records:enterStudents' classLink %}" class="list-group-item">{{className}}</a>
  {% endfor %}
</div>
<h1 class="page-header">... Or add a new class to the list</h1>

<form action="{% url 'records:index' %}" method="post">
{% csrf_token %} 
<div class="form-group">
      <label for="classNumber">Which class do you wish to add?</label>
      <select class="form-control" id="classNumber" name="classNumber">
        <option>1</option>
        <option>2</option>
        <option>3</option>
        <option>4</option>
        <option>5</option>
        <option>6</option>
        <option>7</option>
        <option>8</option>
        <option>9</option>
        <option>10</option>
        <option>11</option>
        <option>12</option>
      </select>
</div>

<div class="form-group">
      <label for="classSection">Which section of that class do you wish to add?</label>
      <select class="form-control" id="classSection" name="classSection">
        <option>A</option>
        <option>B</option>
        <option>C</option>
        <option>D</option>
        <option>E</option>
        <option>F</option>
        <option>G</option>
        <option>H</option>
        <option>I</option>
        <option>J</option>
        <option>K</option>
      </select>
</div>

<input type="submit" value="Add this class" class="btn btn-primary btn-block" role="button">

</form>

{% endblock %}

{% block script %}
<script type="text/javascript">
 $(document).ready(function(){
   {% if alert %}
      //alert('The attendance data for {{classSection}} has been entered. Thank you!');
      swal("Class added!", "You have successfully added a class to PTMNow.", "success")
      // window.location = "http://www.ptmnow.com/records";
   {% endif %}
 });
</script>
{% endblock %}