djangoSchool/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.contrib.auth.views import login, logout
from rest_framework import routers


urlpatterns = [
	url(r'^$','djangoSchool.views.home',name="home"),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^attendance/',include('attendance.urls', namespace="attendance")),
	url(r'^notice/',include('notice.urls', namespace="notice")),
	url(r'^marks/',include('marks.urls', namespace="marks")),
	url(r'^accounts/', include('accounts.urls',namespace="accounts")),
	url(r'^records/', include('records.urls',namespace="records")),
	url(r'^myapi/', include('mywrapper.urls',namespace="mywrapper")),
	url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
	url(r'^attendance2/',include('attendance2.urls', namespace="attendance2")),
]

marks/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$',views.index,name='index'),
	url(r'^viewMarks/(?P<classSection>c[0-9]+[A-Z])/$', views.viewMarks, name='viewMarks'),
	url(r'^viewMarks/(?P<classSection>cNursery[A-Z])/$', views.viewMarks, name='viewMarks'),
	url(r'^enterMarks/(?P<classSection>c[0-9]+[A-Z])/$', views.enterMarks, name='enterMarks'),
	url(r'^enterMarks/(?P<classSection>cNursery[A-Z])/$', views.enterMarks, name='enterMarks'),
]

notice/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$',views.index,name='index'),
	url(r'^class/(?P<classSection>c[0-9]+[A-Z])/$', views.classDetail, name='class'),
	url(r'^class/(?P<classSection>cNursery[A-Z])/$', views.classDetail, name='class'),
]

notice/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import render_to_response
from django.http import HttpResponse
import json,httplib,urllib
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.mail import EmailMessage
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseBadRequest, JsonResponse
from django import forms
from django.template import RequestContext
import django_excel as excel
import pyexcel.ext.xls
import pyexcel.ext.xlsx
import pyexcel
import urllib
from attendance.models import ListOfClasses
from datetime import datetime
from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from .serializers import UserSerializer, GroupSerializer


class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer

# Create your views here.

def getStudentList(classSection,restKey,appKey):
	connection = httplib.HTTPSConnection('api.parse.com', 443)
	params = urllib.urlencode({"where":json.dumps({
		   "Class_Name": '%s' % classSection
		 })})
	connection.connect()
	connection.request('GET', '/1/classes/Class?%s' % params, '', {
		   # "X-Parse-Application-Id": "Sqj2XR5GDdMcXuMsffDQ9yEdzhYJqBZYvDSMLqFC",
		   # "X-Parse-REST-API-Key": "Ox5FKRyiEM33GzS7Ka6oTJCXRIjiPghotbD9dWPx",
		   "X-Parse-Application-Id": appKey,
		   "X-Parse-REST-API-Key": restKey
		 })
	result = json.loads(connection.getresponse().read())
	print result
	return result['results'][0]['Student_Name']

def getUsernames(classSection,restKey,appKey):
	connection = httplib.HTTPSConnection('api.parse.com', 443)
	params = urllib.urlencode({"where":json.dumps({"Class_Name": classSection,}),"limit":999})
	connection.connect()
	connection.request('GET', '/1/classes/_User?%s' % params, '', {
			# "X-Parse-Application-Id": "Sqj2XR5GDdMcXuMsffDQ9yEdzhYJqBZYvDSMLqFC",
		    #   "X-Parse-REST-API-Key": "Ox5FKRyiEM33GzS7Ka6oTJCXRIjiPghotbD9dWPx"
		    "X-Parse-Application-Id": appKey,
		    "X-Parse-REST-API-Key": restKey
			})
	userNames = json.loads(connection.getresponse().read())
	return userNames['results']

def postNoticeData(classSection,json_data,restKey,appKey):
	connection = httplib.HTTPSConnection('api.parse.com', 443)
	connection.connect()
	connection.request('POST', '/1/classes/Notice', json_data, {
		   "X-Parse-Application-Id": appKey,
		   "X-Parse-REST-API-Key": restKey,
		   "Content-Type": "application/json"
		 })
	results = json.loads(connection.getresponse().read())
	print results

@login_required
def index(request):
	latest_class_list = ListOfClasses.objects.filter(schoolUser=request.user);
	classLinks = [p.someClass for p in latest_class_list]
	classNames = [p[1:-1] + " " + p[-1] for p in classLinks]
	zipped_data = zip(classLinks, classNames)
	context = {'item1':"My first string",'classLinks':classLinks,'classNames':classNames,'zipped_data':zipped_data}
	return render(request,'notice/list.html',context)	
	
@login_required
def classDetail(request,classSection):
	latest_class_list = ListOfClasses.objects.filter(schoolUser=request.user);
	classLinks = [p.someClass for p in latest_class_list]
	classNames = [p[1:-1] + " " + p[-1] for p in classLinks]
	zipped_data = zip(classLinks, classNames)
	firstInstance = ListOfClasses.objects.filter(schoolUser=request.user).first()
	restKey = firstInstance.restKey
	javaKey = firstInstance.javaKey
	appKey 	= firstInstance.appKey
	neatSection = classSection[1:-1] + " " + classSection[-1]
	print neatSection
	strippedSection = classSection[1:]
	if request.method == 'POST':
		userNames = getUsernames(classSection,restKey,appKey)
		studentList = getStudentList(classSection,restKey,appKey)
		for student in studentList:
			userdata = (user for user in userNames if user["username"] == classSection+student).next()
			if 'phoneNumber' in userdata:
				myMessage = request.POST['message']
				myMessage = myMessage.replace(u'\xa0', ' ').encode('utf-8')
				myNumber = userdata['phoneNumber']
				params = urllib.urlencode({'user': 'Saurabh', 'password': '123@123', 'mobiles': myNumber, 'sms':myMessage,'senderid':'PTMNOW','version':3})
				f = urllib.urlopen("http://trans.profuseservices.com/sendsms.jsp?%s" % params)
				print f.read()
		data = {}
		data['Category']=request.POST['selectedcategory']
		listClasses = []
		listClasses.append(request.POST['classes'])
		data['Classes'] = listClasses
		data['message'] = request.POST['message']
		json_data = json.dumps(data)
		print json_data
		postNoticeData(classSection,json_data,restKey,appKey)
		return render(request,'notice/list.html',{'alert':'alert','item1':"My first string",'classLinks':classLinks,'classNames':classNames,'zipped_data':zipped_data,'neatSection':neatSection})
	else:
		context = {'classSection':classSection,'neatSection':neatSection,'strippedSection':strippedSection,'javaKey':javaKey,'appKey':appKey}
		return render(request,'notice/notice.html',context)

notice/templates/notice/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="/static/ico/favicon.png">
  <title>{% block title %}{% endblock %}</title>
  <!-- Bootstrap core CSS -->
  <link href="/static/css/bootstrap.min.css" rel="stylesheet">
  <!-- Custom styles for this template -->
  <link href="/static/css/dashboard.css" rel="stylesheet">
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
      <script src="/static/js/date.js"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
      <script type="text/javascript" src="http://www.parsecdn.com/js/parse-latest.js"></script>
      <script src="/static/js/sweetalert.min.js"></script> 
      <link rel="stylesheet" type="text/css" href="/static/css/sweetalert.css">
    </head>

    <body>
      <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid" style="border-bottom: 1px solid darkblue">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="#">School Home</a></li>
              <li><a href="/accounts/logout">Log out</a></li>
            </ul>
            <div class="logoWrapper" style="padding: 25px ">
             <!--  <img src="/static/images/sftwaredev_thumb.gif" alt="BITS Pilani logo"> -->
              <img src="/static/images/kps2.jpg" alt="KPS Logo">
            </div>
          </div>
        </div>
      </nav>

      <div class="container-fluid"  >
        <div class="row">
          <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
              <li><a href="{% url 'attendance:index' %}">Class Attendance</a></li>
              <li class="active"><a href="{% url 'notice:index' %}">Notice Board<span class="sr-only">(current)</span></a></li>
              <li><a href="{% url 'marks:index' %}">Academic Performance</a></li>
            </ul>
            <!-- <ul class="nav nav-sidebar">
              <li><a href="{% url 'records:index' %}">Add/Edit Student Information</a></li>
              <li><a href="">Change password</a></li>
              <li><a href="">Help</a></li>
            </ul>     -->      
          </div>

          <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            {% block content %} {% endblock %}
          </div>
        </div>
      </div>

      {% block script %}
      {% endblock %}
      
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <link href="/static/css/summernote.css" rel="stylesheet">
    <script src="/static/js/summernote.min.js"></script>
  </body>
  </html>

notice/templates/notice/list.html
{% extends 'notice/base.html' %}

{% block title %}Select a class to access its notices{% endblock %}

{% block content %}
<h1 class="page-header">Please pick a class from the list</h1>
<div class="list-group" id="myList">
<!--   <a href="{% url 'notice:class' 'cNurseryA' %}" class="list-group-item">Nursery 'A'</a> -->
 {% for classLink,className in zipped_data %}
  <a href="{% url 'notice:class' classLink %}" class="list-group-item">{{className}}</a>
  {% endfor %}
</div>
{% endblock %}

{% block script %}
<script type="text/javascript">
 $(document).ready(function(){
   {% if alert %}
      //alert('The attendance data for {{classSection}} has been entered. Thank you!');
      swal("Notice submitted!", "The notice has been sent to students of {{neatSection}}. Thank you!", "success")
   {% endif %}
 });
</script>
{% endblock %}

notice/templates/notice/notice.html
{% extends 'notice/base.html' %}

{% block title %}Notices for {{neatSection}}{% endblock %}

{% block content %}
          <h3> Add notice for {{neatSection}}</h3>
          <div class="form-group">
            <label for="subject">What category is this notice in?</label>
            <select class="form-control" id="category" name="category">
              <option selected>General</option>
              <option>Homework</option>
              <option>Examination</option>
            </select>
          </div>
          <div id="policy1"> </div>
          <button id="save1" class="btn btn-primary btn-block" onclick="save1()" type="button" >Send Notice</button>
          <hr>
        
        <hr>
          <div class="table-responsive">
            <table class="table table-striped" id ="myTable">

              </table>
          </div>
           <div>
        <br>
        <button type="button" class="download btn btn-primary btn-block">Download Excel Sheet of past notices</button>
        </div>
        <hr>

  <form action="{% url 'notice:class' classSection %}" method="post" id="myHiddenForm">
  {% csrf_token %} 
  <div class="form-group">
    <input type="hidden" class="form-control" id="message" name="message" value="">
    <input type="hidden" class="form-control" id="selectedcategory" name="selectedcategory" value="">
    <input type="hidden" class="form-control" id="classes" name="classes" value="">
  </div>

  </form>

{% endblock %}

{% block script %}
    <script>
    	var data = '';
    	// Parse.initialize("Sqj2XR5GDdMcXuMsffDQ9yEdzhYJqBZYvDSMLqFC", "EhvA6Aqy067KaSoi6HdVb7Gn5OSMaxr0OwJYqkwJ");
      Parse.initialize("{{appKey}}","{{javaKey}}");
    	var GameScore = Parse.Object.extend("Notice");
		var query = new Parse.Query(GameScore);
		query.equalTo("Classes", "{{strippedSection}}");
		// query.notEqualTo("objectId", "E57WOexIN8");
		//query.ascending("cDate");
		query.find({
		  success: function(results) {
		    //alert("Successfully retrieved " + results.length + " notices.");
		    // This is the code to build a csv object to download Excel-like data
		    data = 'Created At, Category, Message' + '\r\n'



		    // this is the code for filling up the table
		    var out = "<thead><tr><th>" + "Created At" + "</th><th>" + 
    "Category" + "</th><th>" + 
    "Message" +
    "</th></tr></thead><tbody>";     
		    for (var i = 0; i < results.length; i++) {
		      var object = results[i];
		      out+="<tr><td>" + 
        object.createdAt +"</td><td>" +
        object.get('Category') +"</td><td>" +
        object.get('message') +"</td><td>" + "</td></tr>";
        line = ''
         line += '"' + object.createdAt + '"';
        line += ",";
        line += '"' + object.get('Category') + '"';
      line += ",";
      line += '"' + object.get('message') + '"' ;
      data += line + '\r\n';
		      //alert(object.id + ' - ' + object.get('Ram'));
		    }
		    out+="</tbody>";
		    document.getElementById("myTable").innerHTML = out;

		  },
		  error: function(error) {
		    alert("Error: " + error.code + " " + error.message);
		  }
		});
        // Code for downloading CSV starts here
        $(document).ready(function () {
            $('.download').click(function(){
                if(data == '')
                    return;
            CSVDownloader(data, true);
             });

        });
        function CSVDownloader(CSV,ShowLabel) {    
    
    if (CSV == '') {        
         growl.error("Invalid data");
         return;
    }
   
    //var fileName = Date.today().toString('MMMM_dd');
    var fileName = "output"
    if(msieversion()){
    var IEwindow = window.open();
    IEwindow.document.write('sep=,\r\n' + CSV);
    IEwindow.document.close();
    IEwindow.document.execCommand('SaveAs', true, fileName + ".csv");
    IEwindow.close();
    } else {
     var uri = 'data:application/csv;charset=utf-8,' + escape(CSV);
     var link = document.createElement("a");    
     link.href = uri;
     link.style = "visibility:hidden";
     link.download = fileName + ".csv";
     document.body.appendChild(link);
     link.click();
     document.body.removeChild(link);
    }
}
function msieversion() {
    var ua = window.navigator.userAgent; 
    var msie = ua.indexOf("MSIE "); 
    if (msie > 0 || !!navigator.userAgent.match(/Trident.*rv\:11\./)) // If Internet Explorer, return version number 
    {
        return true;
    } else { // If another browser, 
        return false;
    }
        return false; 
}

    </script>

    <script type="text/javascript">

    $(document).ready(function () {
      $('#policy1').summernote({focus: true, height: 200});
       });

    var save1 = function() {
      var policyText1 = $('#policy1').code(); //save HTML If you need(aHTML: array).
      // console.log(policyText1);
      var html = $('<div>' + policyText1 + '</div>');
      var substring = "<p>";
      var plain = '';
      $(html.find('p')).each(function() {
        plain += '\n' + $(this).text();
      });
      // console.log(plain);
      if(policyText1.indexOf(substring) > -1){
	  	policyText1 = String(plain);
	  }
      if(policyText1.length > 300){
        swal("Message too long", "Notices must be less than 320 charecters", "error");
        return;
      }
      

      form = document.getElementById("myHiddenForm");
      // document.getElementById("message").value = policyText1;
      document.getElementById("message").value = policyText1;
      document.getElementById("selectedcategory").value = document.getElementById('category').value;
      document.getElementById("classes").value = "{{strippedSection}}";
      // Define what should happen when the response is loaded
      
      // form.action = "{% url 'notice:class' classSection %}";

      // To be sent, the form needs to be attached to the main document.

      form.submit();
      $('#policy1').destroy();
    

    // var GameScore = Parse.Object.extend("Notice");
    // var gameScore = new GameScore();
    // var selectedCategory = document.getElementById('category').value

    // gameScore.set("Category", selectedCategory);
    // gameScore.set("Classes", ['{{strippedSection}}']);
    // gameScore.set("message", policyText1);

    // gameScore.save(null, {
    //   success: function(gameScore) {
    //     // Execute any logic that should take place after the object is saved.
    //     // alert('Your notice had been sent. Reload page to send another notice');
    //     swal("Notice sent!", "Reload page to send another notice", "success")
    //   },
    //   error: function(gameScore, error) {
    //     // Execute any logic that should take place if the save fails.
    //     // error is a Parse.Error with an error code and message.
    //     swal("Failed to send notice", "There seems to be an error. Try again or contact support", "error")
    //     //alert('Failed to create new object, with error code: ' + error.message);
    //   }
    //       });


  }       

    </script>

{% endblock %}