attendance2/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$',views.index,name='index'),
	url(r'^viewAttendance/(?P<classSection>c[0-9]+[A-Z])/$', views.viewAttendance, name='viewAttendance'),
	url(r'^viewAttendance/(?P<classSection>cNursery[A-Z])/$', views.viewAttendance, name='viewAttendance'),
	url(r'^enterAttendance/(?P<classSection>c[0-9]+[A-Z])/$', views.enterAttendance, name='enterAttendance'),
	url(r'^enterAttendance/(?P<classSection>cNursery[A-Z])/$', views.enterAttendance, name='enterAttendance'),
	url(r'^uploadAttendance/(?P<classSection>cNursery[A-Z])/$', views.uploadAttendance, name='uploadAttendance'),
]

djangoSchool/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.contrib.auth.views import login, logout
from rest_framework import routers


urlpatterns = [
	url(r'^$','djangoSchool.views.home',name="home"),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^attendance/',include('attendance.urls', namespace="attendance")),
	url(r'^notice/',include('notice.urls', namespace="notice")),
	url(r'^marks/',include('marks.urls', namespace="marks")),
	url(r'^accounts/', include('accounts.urls',namespace="accounts")),
	url(r'^records/', include('records.urls',namespace="records")),
	url(r'^myapi/', include('mywrapper.urls',namespace="mywrapper")),
	url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
	url(r'^attendance2/',include('attendance2.urls', namespace="attendance2")),
]

marks/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$',views.index,name='index'),
	url(r'^viewMarks/(?P<classSection>c[0-9]+[A-Z])/$', views.viewMarks, name='viewMarks'),
	url(r'^viewMarks/(?P<classSection>cNursery[A-Z])/$', views.viewMarks, name='viewMarks'),
	url(r'^enterMarks/(?P<classSection>c[0-9]+[A-Z])/$', views.enterMarks, name='enterMarks'),
	url(r'^enterMarks/(?P<classSection>cNursery[A-Z])/$', views.enterMarks, name='enterMarks'),
]

attendance2/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import render_to_response
from django.http import HttpResponse
import json,httplib,urllib
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.mail import EmailMessage
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseBadRequest, JsonResponse
from django import forms
from django.template import RequestContext
import django_excel as excel
import pyexcel.ext.xls
import pyexcel.ext.xlsx
import pyexcel
import urllib
from attendance.models import ListOfClasses
from datetime import datetime
from mywrapper.models import Grade

# Create your views here.

def getStudentList(classSection,restKey,appKey):
	connection = httplib.HTTPSConnection('api.parse.com', 443)
	params = urllib.urlencode({"where":json.dumps({
		   "Class_Name": '%s' % classSection
		 })})
	connection.connect()
	connection.request('GET', '/1/classes/Class?%s' % params, '', {
		   # "X-Parse-Application-Id": "Sqj2XR5GDdMcXuMsffDQ9yEdzhYJqBZYvDSMLqFC",
		   # "X-Parse-REST-API-Key": "Ox5FKRyiEM33GzS7Ka6oTJCXRIjiPghotbD9dWPx",
		   "X-Parse-Application-Id": appKey,
		   "X-Parse-REST-API-Key": restKey
		 })
	result = json.loads(connection.getresponse().read())
	# print result
	return result['results'][0]['Student_Name']

def getUsernames(classSection,restKey,appKey):
	connection = httplib.HTTPSConnection('api.parse.com', 443)
	params = urllib.urlencode({"where":json.dumps({"Class_Name": classSection,}),"limit":999})
	connection.connect()
	connection.request('GET', '/1/classes/_User?%s' % params, '', {
			# "X-Parse-Application-Id": "Sqj2XR5GDdMcXuMsffDQ9yEdzhYJqBZYvDSMLqFC",
		    #   "X-Parse-REST-API-Key": "Ox5FKRyiEM33GzS7Ka6oTJCXRIjiPghotbD9dWPx"
		    "X-Parse-Application-Id": appKey,
		    "X-Parse-REST-API-Key": restKey
			})
	userNames = json.loads(connection.getresponse().read())
	return userNames['results']

def postAttendanceData(classSection,json_data,restKey,appKey):
	connection = httplib.HTTPSConnection('api.parse.com', 443)
	connection.connect()
	connection.request('POST', '/1/classes/' + classSection , json_data, {
		   # "X-Parse-Application-Id": "Sqj2XR5GDdMcXuMsffDQ9yEdzhYJqBZYvDSMLqFC",
		   # "X-Parse-REST-API-Key": "Ox5FKRyiEM33GzS7Ka6oTJCXRIjiPghotbD9dWPx",
		   "X-Parse-Application-Id": appKey,
		   "X-Parse-REST-API-Key": restKey,
		   "Content-Type": "application/json"
		 })
	results = json.loads(connection.getresponse().read())
	#print results


@login_required
def index(request):
	latest_class_list = Grade.objects.all()	
	classLinks =  [p.fullGradeID for p in latest_class_list]
	classNames = [p[1:-1] + " " + p[-1] for p in classLinks]
	zipped_data = zip(classLinks, classNames)
	context = {'item1':"My first string",'classLinks':classLinks,'classNames':classNames,'zipped_data':zipped_data}
	return render(request,'attendance2/list.html',context)	

@login_required
def viewAttendance(request,classSection):
	firstInstance = ListOfClasses.objects.filter(schoolUser=request.user).first()
	restKey = firstInstance.restKey
	javaKey = firstInstance.javaKey
	appKey 	= firstInstance.appKey
	neatSection = classSection[1:-1] + " " + classSection[-1]
	strippedSection = classSection[1:]	
	context = {'classSection':classSection,'neatSection':neatSection,'strippedSection':strippedSection,'appKey':appKey,'javaKey':javaKey}
	return render(request,'attendance2/viewAttendance.html',context)

@login_required
def enterAttendance(request,classSection):

	# studentList = 
	if request.method == 'POST':
		# userNames = getUsernames(classSection,restKey,appKey)
		# absentStudents = request.POST
		# data = {}
		# data['cDate'] = request.POST['date']
		# dateOfAttendance = data['cDate']
		# myDateObject = datetime.strptime(dateOfAttendance,'%d/%m/%Y')
		# myDateObject = myDateObject.strftime("%d %B %Y")
		# # For loop to iterate over list of students and assign 'A' or 'P'.
		# # Also sends emails to absent students' parents
		# for student in studentList:
		# 	studentMod = student.replace (" ", "_")
		# 	studentMod = "R" + studentMod
		# 	if(student in absentStudents):
		# 		data[studentMod] = "A"
		# 		userdata = (user for user in userNames if user["username"] == classSection+student).next()
		# 		# if 'email' in userdata:
		# 		# 	print 'email the person!'
		# 		# 	email = EmailMessage('Hello there', 'well well, your son was absent today', to=[userdata['email']])
		# 		# 	print userdata['email']
		# 		# 	email.send()
		# 		# else:
		# 		# 	print 'ask them to enter their e-mail!'
		# 		if 'phoneNumber' in userdata:
		# 			# print 'Starting now'
		# 			try:
		# 				childName = userdata["username"].split()
		# 				childName = childName[1:]
		# 				childName = " ".join(childName)
		# 			except:
		# 				childName = "Your child"
		# 			myMessage =  childName + ' was absent on ' + myDateObject + '\r\n - Kerala Public School'
		# 			myNumber = userdata['phoneNumber']
		# 			print childName
		# 			# print 'Is this where I go wrong?'
		# 			params = urllib.urlencode({'user': 'Saurabh', 'password': '123@123', 'mobiles': myNumber, 'sms':myMessage,'senderid':'PTMNOW','version':3})
		# 			# print 'Or here?'
		# 			f = urllib.urlopen("http://trans.profuseservices.com/sendsms.jsp?%s" % params)
		# 			print f.read()
		# 	else:
		# 		data[studentMod] = "P"
		# start = dateOfAttendance.find('/')
		# end = dateOfAttendance.rfind('/')
		# data['mdate'] = int(dateOfAttendance[start+1:end])
		# json_data = json.dumps(data)
		# postAttendanceData(classSection,json_data,restKey,appKey)					
		# # return HttpResponseRedirect(reverse('attendance:index'))
		return redirect(reverse('attendance:index'), {'alert':'alert'})
		# return render(request,'attendance2/list.html',{'alert':'alert',"classSection":classSection,'classLinks':classLinks,'classNames':classNames,'zipped_data':zipped_data})
	else:	
		neatSection = classSection
		strippedSection = classSection
		context = {'classSection':classSection,'neatSection':neatSection,'strippedSection':strippedSection,'studentList':studentList}
		# return redirect(reverse('attendance:index'), {"alert":"alert"})
		return render(request,'attendance2/enterAttendance.html',context)

class UploadFileForm(forms.Form):
	file = forms.FileField()

@login_required
def uploadAttendance(request,classSection):
	if request.method == "POST":
		form = UploadFileForm(request.POST, request.FILES)
		if form.is_valid():
			filehandle = request.FILES['file']
			attendanceExcel = request.FILES['file'].get_array()
			for i in range(1,len(attendanceExcel)):
				print attendanceExcel[i]
	else:
		form = UploadFileForm()
	return render_to_response(
		'attendance2/uploadAttendance.html',
		{
			'form': form,
			'title': 'Excel file upload and download example',
			'header': 'Please choose any excel file from your cloned repository:'
		},
		context_instance=RequestContext(request))

attendance2/templates/attendance2/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="/static/ico/favicon.png">
  <title>{% block title %}{% endblock %}</title>
  <style type="text/css">
    body {
      min-height: 2000px;
      padding-top: 70px;
    }
    .tableFloatingHeaderOriginal th {
      background-color: #fff;
      border-bottom: 1px solid #DDD;
    }
  </style>
  <!-- Bootstrap core CSS -->
  <link href="/static/css/bootstrap.min.css" rel="stylesheet">
  <!-- Custom styles for this template -->
  <link href="/static/css/dashboard.css" rel="stylesheet">
  <link href="/static/css/jquery-ui.min.css" rel="stylesheet">
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
      <script src="/static/js/date.js"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
      <script src="/static/js/jquery-ui.min.js"></script>

      <script type="text/javascript" src="http://www.parsecdn.com/js/parse-latest.js"></script>
      <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.0/css/bootstrap-toggle.min.css" rel="stylesheet">
      <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.0/js/bootstrap-toggle.min.js"></script>
      <script src="/static/js/jquery.stickytableheaders.min.js"></script>
      <script src="/static/js/bootstrap.min.js"></script>
      <script src="/static/js/sweetalert.min.js"></script> 
      <link rel="stylesheet" type="text/css" href="/static/css/sweetalert.css">

    </head>

    <body>
      <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid" style="border-bottom: 1px solid darkblue">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="#">School Home</a></li>
              <li><a href="/accounts/logout">Log out</a></li>
            </ul>
            
            <div class="logoWrapper" style="padding: 25px ">
              <!-- <img src="/static/images/sftwaredev_thumb.gif" alt="BITS Pilani logo"> -->
              <img src="/static/images/kps2.jpg" alt="KPS Logo">
            </div>
          </div>
        </div>
      </nav>

      <div class="container-fluid"  >
        <div class="row">
          <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
              <li class="active"><a href="{% url 'attendance:index' %}">Class Attendance<span class="sr-only">(current)</span></a></li>
              <li><a href="{% url 'notice:index' %}">Notice Board</a></li>
              <li><a href="{% url 'marks:index' %}">Academic Performance</a></li>
            </ul>
            <!-- <ul class="nav nav-sidebar">
              <li><a href="{% url 'records:index' %}">Add/Edit Student Information</a></li>
              <li><a href="">Change password</a></li>
              <li><a href="">Help</a></li>
            </ul>     -->      
          </div>

          <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            {% block content %} {% endblock %}
          </div>
        </div>
      </div>

      {% block script %}
      {% endblock %}

  </body>
  </html>

attendance2/templates/attendance2/enterAttendance.html
{% extends 'attendance/base.html' %}
{% block title %}Enter Attendance for {{neatSection}} {% endblock %}

{% block content %}
<h1 class="page-header">{{neatSection}}</h1>

<div>
	<br>

<a href="{% url 'attendance:viewAttendance' classSection %}" class="btn btn-primary btn-block" role="button">View Attendance for this class</a>

<!-- <a href="{% url 'attendance:viewAttendance' 'cNurseryA' %}" class="btn btn-primary btn-block" role="button">View Attendance for this class</a> -->

</div>
<hr>

<form action="{% url 'attendance:enterAttendance' classSection %}" method="post">
{% csrf_token %} 
<div class="form-group">
  <label for="date">What date is this attendance for? </label>
  <input type="text" class="form-control" id="date" name="date">
</div>
<table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>Student's Name</th>
        <th>Present/Absent</th>
      </tr>
    </thead>
    <tbody>

{% for o in studentList %}
<tr>
        <td><label>{{o}}</label></td>
        <td><div class="form-group">
  			<input type="checkbox" name="{{o}}" data-toggle="toggle" data-on="Absent" data-off="Present" data-onstyle="danger" data-offstyle="success">
		</div></td>
    </tr>
{% endfor %}
</tbody>
  </table>

<input type="submit" value="Submit Attendance" class="btn btn-primary btn-block" role="button">

</form>
<hr>

{% endblock %}

{% block script %}
<script>
$( "#date" ).datepicker(
	{dateFormat: "d/m/yy"});
</script>

{% endblock %}

attendance2/templates/attendance2/list.html
{% extends 'attendance/base.html' %}

{% block title %}[This uses API 2.0] Select class to enter attendance for{% endblock %}

{% block content %}
<h1 class="page-header"> [This uses API 2.0] Please pick a class from the list</h1>
<div class="list-group" id="myList">
{% for classLink,className in zipped_data %}
<!--   <a href="{% url 'attendance:enterAttendance' 'cNurseryA' %}" class="list-group-item">Nursery 'A'</a>
  <a href="{% url 'attendance:enterAttendance' 'c1A' %}" class="list-group-item">Class 1 'A'</a> -->
  <a href="{% url 'attendance:enterAttendance' classLink %}" class="list-group-item">{{className}}</a>
<!--   <a href="{% url 'attendance:enterAttendance' 'c1C' %}" class="list-group-item">Class 1 'C'</a>
  <a href="{% url 'attendance:enterAttendance' 'c1D' %}" class="list-group-item">Class 1 'D'</a> -->
  {% endfor %}
</div>
{% endblock %}

{% block script %}
<script type="text/javascript">
 $(document).ready(function(){
   {% if alert %}
      //alert('The attendance data for {{classSection}} has been entered. Thank you!');
      swal("Attendance submitted!", "Data for {{classSection}} has been entered. Thank you!", "success")
   {% endif %}
 });
</script>
{% endblock %}

attendance2/templates/attendance2/uploadAttendance.html
{% extends 'attendance/base.html' %}
{% block title %}Upload attendance for {{neatSection}} {% endblock %}
{% block content %}

    <h1>{{header}}</h1>

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" enctype="multipart/form-data"  method="post">
        <table>
            {{ form.as_table }}
        </table>
        {% csrf_token %}
        <input type="submit" value="Submit">
    </form>
    {% endblock %}
{% block script %}
{% endblock %}

attendance2/templates/attendance2/viewAttendance.html
{% extends 'attendance/base.html' %}
{% block title %}View attendance for {{neatSection}} {% endblock %}
{% block content %}
<h1 class="page-header">{{neatSection}}</h1>
<div>
	<br>
	<button type="button" class="download btn btn-primary btn-block">Download Excel Sheet</button>
</div>
<hr>
<div class="table-responsive">
	<table class="table table-striped" id ="myTable">
	</table>
</div>
{% endblock %}

{% block script %}
<script>
	var data = '';
	// Parse.initialize("Sqj2XR5GDdMcXuMsffDQ9yEdzhYJqBZYvDSMLqFC", "EhvA6Aqy067KaSoi6HdVb7Gn5OSMaxr0OwJYqkwJ");
	Parse.initialize("{{appKey}}","{{javaKey}}");
	var GameScore = Parse.Object.extend("{{classSection}}");
	var query = new Parse.Query(GameScore);
	query.notEqualTo("objectId", "E57WOexIN8");
	query.ascending("createdAt");
	var studentListObject = Parse.Object.extend("Class");
	var queryStudent = new Parse.Query(studentListObject);
	queryStudent.equalTo("Class_Name","{{classSection}}");
	var trial;
	queryStudent.find({
		success: function(results) {
			trial = results[0].get('Student_Name');
			return trial;
		},
		error: function(error) {
			alert("Error: " + error.code + " " + error.message);
		}
	}).then(function(results) {
		query.find({
			success: function(results) {

// This is the code to build a csv object to download Excel-like data

// this is the code for filling up the table
var out = "<thead><tr><th>" + "cDate" + "</th><th>"
data = 'cDate';

for(var k = 0; k < trial.length; k++){
	out+= trial[k] + "</th><th>";
	data += "," + trial[k]; 
}
data += '\r\n';
out+="</th></tr></thead><tbody>";     
for (var i = 0; i < results.length; i++) {
	var object = results[i];
	out+="<tr><td>" + 
	object.get('cDate') +"</td><td>";
	line = '';
	line += '"' + object.get('cDate') + '"';
	for(var j = 0; j < trial.length; j++){
		var column = trial[j].replace(/ /g, "_");
		column = "R" + column;
		out+= object.get(column) +"</td><td>";
		line += ",";
		line += '"' + object.get(column)+ '"';
	}
	out += "</td></tr>";
	data += line + '\r\n';

}
out+="</tbody>";
document.getElementById("myTable").innerHTML = out;
var offset = $('.navbar').height();
$("html:not(.legacy) table").stickyTableHeaders({fixedOffset: offset});
}})
}); // close then function


// Code for downloading CSV starts here
$(document).ready(function () {
	$('.download').click(function(){
		if(data == '')
			return;
		CSVDownloader(data, true);
	});

});
function CSVDownloader(CSV,ShowLabel) {    

	if (CSV == '') {        
		growl.error("Invalid data");
		return;
	}

//var fileName = Date.today().toString('MMMM_dd');
var fileName = "output"
if(msieversion()){
	var IEwindow = window.open();
	IEwindow.document.write('sep=,\r\n' + CSV);
	IEwindow.document.close();
	IEwindow.document.execCommand('SaveAs', true, fileName + ".csv");
	IEwindow.close();
} else {
	var uri = 'data:application/csv;charset=utf-8,' + escape(CSV);
	var link = document.createElement("a");    
	link.href = uri;
	link.style = "visibility:hidden";
	link.download = fileName + ".csv";
	document.body.appendChild(link);
	link.click();
	document.body.removeChild(link);
}
}
function msieversion() {
	var ua = window.navigator.userAgent; 
	var msie = ua.indexOf("MSIE "); 
if (msie > 0 || !!navigator.userAgent.match(/Trident.*rv\:11\./)) // If Internet Explorer, return version number 
{
	return true;
} else { // If another browser, 
	return false;
}
return false; 
}

</script>

{% endblock %}