djangoSchool/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.contrib.auth.views import login, logout
from rest_framework import routers


urlpatterns = [
	url(r'^$','djangoSchool.views.home',name="home"),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^attendance/',include('attendance.urls', namespace="attendance")),
	url(r'^notice/',include('notice.urls', namespace="notice")),
	url(r'^marks/',include('marks.urls', namespace="marks")),
	url(r'^accounts/', include('accounts.urls',namespace="accounts")),
	url(r'^records/', include('records.urls',namespace="records")),
	url(r'^myapi/', include('mywrapper.urls',namespace="mywrapper")),
	url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
	url(r'^attendance2/',include('attendance2.urls', namespace="attendance2")),
]

marks/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$',views.index,name='index'),
	url(r'^viewMarks/(?P<classSection>c[0-9]+[A-Z])/$', views.viewMarks, name='viewMarks'),
	url(r'^viewMarks/(?P<classSection>cNursery[A-Z])/$', views.viewMarks, name='viewMarks'),
	url(r'^enterMarks/(?P<classSection>c[0-9]+[A-Z])/$', views.enterMarks, name='enterMarks'),
	url(r'^enterMarks/(?P<classSection>cNursery[A-Z])/$', views.enterMarks, name='enterMarks'),
]

marks/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from django.http import HttpResponse
import json,httplib,urllib
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from attendance.models import ListOfClasses

# Create your views here.

@login_required
def index(request):
	latest_class_list = ListOfClasses.objects.filter(schoolUser=request.user);
	classLinks = [p.someClass for p in latest_class_list]
	classNames = [p[1:-1] + " " + p[-1] for p in classLinks]
	zipped_data = zip(classLinks, classNames)
	context = {'item1':"My first string",'classLinks':classLinks,'classNames':classNames,'zipped_data':zipped_data}
	return render(request,'marks/list.html',context)	

@login_required
def viewMarks(request,classSection):
	firstInstance = ListOfClasses.objects.filter(schoolUser=request.user).first()
	restKey = firstInstance.restKey
	javaKey = firstInstance.javaKey
	appKey 	= firstInstance.appKey
	neatSection = classSection[1:-1] + " " + classSection[-1]
	strippedSection = classSection[1:]
	context = {'classSection':classSection,'neatSection':neatSection,'strippedSection':strippedSection,'appKey':appKey,'javaKey':javaKey}
	return render(request,'marks/viewMarks.html',context)
	
@login_required
def enterMarks(request,classSection):
	firstInstance = ListOfClasses.objects.filter(schoolUser=request.user).first()
	restKey = firstInstance.restKey
	javaKey = firstInstance.javaKey
	appKey 	= firstInstance.appKey

	connection = httplib.HTTPSConnection('api.parse.com', 443)
	params = urllib.urlencode({"where":json.dumps({
	       "Class_Name": '%s' % classSection
	     })})
	connection.connect()
	connection.request('GET', '/1/classes/Class?%s' % params, '', {
	       # "X-Parse-Application-Id": "Sqj2XR5GDdMcXuMsffDQ9yEdzhYJqBZYvDSMLqFC",
	       # "X-Parse-REST-API-Key": "Ox5FKRyiEM33GzS7Ka6oTJCXRIjiPghotbD9dWPx"
	       "X-Parse-Application-Id": appKey,
	       "X-Parse-REST-API-Key": restKey
	     })
	result = json.loads(connection.getresponse().read())
	studentList = result['results'][0]['Student_Name']

	if request.method == 'POST':
		latest_class_list = ListOfClasses.objects.filter(schoolUser=request.user);
		classLinks = [p.someClass for p in latest_class_list]
		classNames = [p[1:-1] + " " + p[-1] for p in classLinks]
		zipped_data = zip(classLinks, classNames)

		submittedData = request.POST
		data = {}
		for student in studentList:
			studentMod = student.replace (" ", "_")
			studentMod = "R" + studentMod
			if submittedData[student] == "":
				data[studentMod] = -1
			else:
				data[studentMod] = int(submittedData[student])

		data['cDate'] = submittedData['date']
		data['Category'] = submittedData['category']
		data['MaxMarks'] = int(submittedData['total'])
		data['Subject'] = submittedData['subject']
		data['UMI'] = submittedData['date'] + classSection + submittedData['subject'] + submittedData['category']
		json_data = json.dumps(data)

		connection = httplib.HTTPSConnection('api.parse.com', 443)
		connection.connect()
		connection.request('POST', '/1/classes/Marks' + classSection, json_data, {
		       # "X-Parse-Application-Id": "Sqj2XR5GDdMcXuMsffDQ9yEdzhYJqBZYvDSMLqFC",
		       # "X-Parse-REST-API-Key": "Ox5FKRyiEM33GzS7Ka6oTJCXRIjiPghotbD9dWPx",
		       "X-Parse-Application-Id": appKey,
		       "X-Parse-REST-API-Key": restKey,
		       "Content-Type": "application/json"
		     })
		results = json.loads(connection.getresponse().read())
		# print results					
		# return HttpResponseRedirect(reverse('marks:index'))
		# return render(request,'marks/list.html',{'alert':'alert',"classSection":classSection,'classLinks':classLinks,'classNames':classNames,'zipped_data':zipped_data})
		# return HttpResponse(json_data)
		return render(request,'marks/list.html',{'alert':'alert',"classSection":classSection,'classLinks':classLinks,'classNames':classNames,'zipped_data':zipped_data})
		# return render(request,'attendance/list.html',{'alert':'alert',"classSection":classSection,'classLinks':classLinks,'classNames':classNames,'zipped_data':zipped_data})

	else:	
		neatSection = classSection[1:-1] + " " + classSection[-1]
		strippedSection = classSection[1:]

		context = {'classSection':classSection,'neatSection':neatSection,'strippedSection':strippedSection,'studentList':studentList}
		return render(request,'marks/enterMarks.html',context)

marks/templates/marks/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="/static/ico/favicon.png">
  <title>{% block title %}{% endblock %}</title>
  <style type="text/css">
    body {
      min-height: 2000px;
      padding-top: 70px;
    }
    .tableFloatingHeaderOriginal th {
      background-color: #fff;
      border-bottom: 1px solid #DDD;
    }
  </style>
  <!-- Bootstrap core CSS -->
  <link href="/static/css/bootstrap.min.css" rel="stylesheet">
  <!-- Custom styles for this template -->
  <link href="/static/css/dashboard.css" rel="stylesheet">
  <link href="/static/css/jquery-ui.min.css" rel="stylesheet">
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
      <script src="/static/js/date.js"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
      <script src="/static/js/jquery-ui.min.js"></script>

      <script type="text/javascript" src="http://www.parsecdn.com/js/parse-latest.js"></script>
      <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.0/css/bootstrap-toggle.min.css" rel="stylesheet">
      <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.0/js/bootstrap-toggle.min.js"></script>
      <script src="/static/js/jquery.stickytableheaders.min.js"></script>
      <script src="/static/js/bootstrap.min.js"></script>
      <script src="/static/js/sweetalert.min.js"></script> 
      <link rel="stylesheet" type="text/css" href="/static/css/sweetalert.css">    
    </head>

    <body>
      <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid" style="border-bottom: 1px solid darkblue">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="#">School Home</a></li>
              <li><a href="/accounts/logout">Log out</a></li>
            </ul>
            <div class="logoWrapper" style="padding: 25px ">
              <!-- <img src="/static/images/sftwaredev_thumb.gif" alt="BITS Pilani logo"> -->
               <img src="/static/images/kps2.jpg" alt="KPS Logo">
            </div>
          </div>
        </div>
      </nav>

      <div class="container-fluid"  >
        <div class="row">
          <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
              <li><a href="{% url 'attendance:index' %}">Class Attendance</a></li>
              <li><a href="{% url 'notice:index' %}">Notice Board</a></li>
              <li class="active"><a href="{% url 'marks:index' %}">Academic Performance<span class="sr-only">(current)</span></a></li>
            </ul>
            <!-- <ul class="nav nav-sidebar">
              <li><a href="{% url 'records:index' %}">Add/Edit Student Information</a></li>
              <li><a href="">Change password</a></li>
              <li><a href="">Help</a></li>
            </ul>      -->     
          </div>

          <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            {% block content %} {% endblock %}
          </div>
        </div>
      </div>

      {% block script %}
      {% endblock %}
      
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

  </body>
  </html>

marks/templates/marks/enterMarks.html
{% extends 'marks/base.html' %}
{% block title %}Enter marks for {{neatSection}} {% endblock %}

{% block content %}
<h1 class="page-header">{{neatSection}}</h1>

<div>
	<br>

<a href="{% url 'marks:viewMarks' classSection %}" class="btn btn-primary btn-block" role="button">View Marks for this class</a>

</div>
<hr>

<form action="{% url 'marks:enterMarks' classSection %}" method="POST" >
{% csrf_token %} 

<div class="form-group">
  <label for="date">What date are these marks for? </label>
  <input type="text" class="form-control" id="date" name="date">
</div>
<div class="form-group">
      <label for="subject">What subject are these marks for?</label>
      <select class="form-control" id="subject" name="subject">
        <option>Hindi</option>
        <option>English</option>
        <option>Math</option>
        <option>Science</option>
      </select>
</div>
      <div class="form-group">
      <label for="category">What category do these marks belong to?</label>
      <select class="form-control" id="category" name="category">
        <option>Final</option>
        <option>Half-yearly</option>
        <option>Weekly</option>
        <option>Assignment</option>
      </select>
</div>

<div class="form-group">
  <label for="total">What is the total marks for the paper? [Numbers only, example, 100]</label>
  <input type="text" class="form-control" id="total" name="total">
</div>

<table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>Student's Name</th>
        <th>Student's Marks</th>
      </tr>
    </thead>
    <tbody>

{% for o in studentList %}
<tr>
        <td><label for="total">{{o}}</label></td>
        <td><div class="form-group">
  			<input type="text" class="form-control" name="{{o}}">
		</div></td>
    </tr>
{% endfor %}
</tbody>
  </table>
<input type="submit" value="Submit Marks" class="btn btn-primary btn-block" role="button">

</form>
<hr>

{% endblock %}

{% block script %}
<script>
$( "#date" ).datepicker(
	{dateFormat: "d/m/yy"});

</script>

{% endblock %}

marks/templates/marks/list.html
{% extends 'marks/base.html' %}

{% block title %}Select class to enter marks for{% endblock %}

{% block content %}
<h1 class="page-header">Please pick a class from the list</h1>
<div class="list-group" id="myList">
 {% for classLink,className in zipped_data %}
  <a href="{% url 'marks:enterMarks' classLink %}" class="list-group-item">{{className}}</a>
 <!--  <a href="{% url 'marks:enterMarks' 'c1A' %}" class="list-group-item">Class 1 'A'</a> -->
  {% endfor %}
</div>
{% endblock %}

{% block script %}
<script type="text/javascript">
 $(document).ready(function(){
   {% if alert %}
      //alert('The attendance data for {{classSection}} has been entered. Thank you!');
      swal("Marks submitted!", "Data for {{classSection}} has been entered. Thank you!", "success")
   {% endif %}
 });
</script>
{% endblock %}

marks/templates/marks/viewMarks.html
{% extends 'marks/base.html' %}
{% block title %}View marks for {{neatSection}} {% endblock %}
`
{% block content %}
<h1 class="page-header">{{neatSection}}</h1>
<div>
	<br>
	<button type="button" class="download btn btn-primary btn-block">Download Excel Sheet</button>
</div>
<hr>
<div class="table-responsive">
	<table class="table table-striped" id ="myTable">
	</table>
</div>
{% endblock %}

{% block script %}
<script>
	var data = '';
	// Parse.initialize("Sqj2XR5GDdMcXuMsffDQ9yEdzhYJqBZYvDSMLqFC", "EhvA6Aqy067KaSoi6HdVb7Gn5OSMaxr0OwJYqkwJ");
	Parse.initialize("{{appKey}}","{{javaKey}}");
	var tableToLoad = "Marks" + "{{classSection}}"
	var GameScore = Parse.Object.extend(tableToLoad);
	var query = new Parse.Query(GameScore);
	query.notEqualTo("objectId", "E57WOexIN8");
	query.ascending("createdAt");
	var studentListObject = Parse.Object.extend("Class");
	var queryStudent = new Parse.Query(studentListObject);
	queryStudent.equalTo("Class_Name","{{classSection}}");
	var trial;
	queryStudent.find({
		success: function(results) {
			// trial stores the list of student names
			trial = results[0].get('Student_Name');
			return trial;
		},
		error: function(error) {
			alert("Error: " + error.code + " " + error.message);
		}
	}).then(function(results) {
		query.find({
			success: function(results) {

// This is the code to build a csv object to download Excel-like data\
// This is also the code for filling up the table
// results refers to the entire table of data
// trial refers to individual students
var out = "<thead><tr><th>" + "cDate" + "</th><th>Subject</th><th>Category</th><th>Max Marks</th><th>"
data = 'cDate, Subject, Category, Max Marks';

for(var k = 0; k < trial.length; k++){
	out+= trial[k] + "</th><th>";
	data += "," + trial[k]; 
}
data += '\r\n';
// just finished filling up the header
out+="</th></tr></thead><tbody>";     
for (var i = 0; i < results.length; i++) {
	var object = results[i];
	out+="<tr><td>" + 
	object.get('cDate') +"</td><td>" +
	object.get('Subject') +"</td><td>" +
	object.get('Category') +"</td><td>" +
	object.get('MaxMarks') +"</td><td>"
	line = '';
	line += '"' + object.get('cDate') + '",';
	line += '"' + object.get('Subject') + '",';
	line += '"' + object.get('Category') + '",';
	line += '"' + object.get('MaxMarks') + '"';
	for(var j = 0; j < trial.length; j++){
		var column = trial[j].replace(/ /g, "_");
		column = "R" + column;
		out+= object.get(column) +"</td><td>";
		line += ",";
		line += '"' + object.get(column)+ '"';
	}
	out += "</td></tr>";
	data += line + '\r\n';

}
out+="</tbody>";
document.getElementById("myTable").innerHTML = out;
var offset = $('.navbar').height();
$("html:not(.legacy) table").stickyTableHeaders({fixedOffset: offset});
}})
}); // close then function


// Code for downloading CSV starts here
$(document).ready(function () {
	$('.download').click(function(){
		if(data == '')
			return;
		CSVDownloader(data, true);
	});

});
function CSVDownloader(CSV,ShowLabel) {    

	if (CSV == '') {        
		growl.error("Invalid data");
		return;
	}

//var fileName = Date.today().toString('MMMM_dd');
var fileName = "output"
if(msieversion()){
	var IEwindow = window.open();
	IEwindow.document.write('sep=,\r\n' + CSV);
	IEwindow.document.close();
	IEwindow.document.execCommand('SaveAs', true, fileName + ".csv");
	IEwindow.close();
} else {
	var uri = 'data:application/csv;charset=utf-8,' + escape(CSV);
	var link = document.createElement("a");    
	link.href = uri;
	link.style = "visibility:hidden";
	link.download = fileName + ".csv";
	document.body.appendChild(link);
	link.click();
	document.body.removeChild(link);
}
}
function msieversion() {
	var ua = window.navigator.userAgent; 
	var msie = ua.indexOf("MSIE "); 
if (msie > 0 || !!navigator.userAgent.match(/Trident.*rv\:11\./)) // If Internet Explorer, return version number 
{
	return true;
} else { // If another browser, 
	return false;
}
return false; 
}

</script>

{% endblock %}